version: "3.9"
name: postgres_lab 
services: 
  postgres: 
    container_name: ${CONTAINER_NAME} 
    image: postgres:${POSTGRES_VERSION}
    env_file: ./.env 
    environment: 
      - TZ=America/Argentina/Buenos_Aires
    ports: 
      - ${POSTGRES_PORT}:5432
    restart: always
    volumes: 
      - ./docker/volumes/data:/var/lib/postgresql/data
      - ./docker/volumes/backups:/backups
    extra_hosts:
      - host.docker.internal:host-gateway 
  


