version: '3.9'
name: django-postgres

services:
  postgres:
    image: postgres:16.2

    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    
    ports:
      - "${DB_PORT}:5432"

    volumes:
      - ./docker/data:/var/lib/postgresql/data
      - ./docker/backups:/backups


