# Generated by Django 5.0.3 on 2024-05-03 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('route', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='fk_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route'),
        ),
        migrations.AddField(
            model_name='flight',
            name='fk_flight_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flighthistory'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='flighthistory',
            name='fk_plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.plane'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fk_flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fk_itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.itinerary'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
