# Generated by Django 5.0.3 on 2024-05-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
